==1359610== Helgrind, a thread error detector
==1359610== Copyright (C) 2007-2017, and GNU GPL'd, by OpenWorks LLP et al.
==1359610== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==1359610== Command: ./philo 5 800 200 200 5
==1359610== 
==1359610== ---Thread-Announcement------------------------------------------
==1359610== 
==1359610== Thread #3 was created
==1359610==    at 0x49A09F3: clone (clone.S:76)
==1359610==    by 0x49A18EE: __clone_internal (clone-internal.c:83)
==1359610==    by 0x490F6D8: create_thread (pthread_create.c:295)
==1359610==    by 0x49101FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==1359610==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x40225D: ph_threading (threading.c:64)
==1359610==    by 0x40121E: main (main.c:43)
==1359610== 
==1359610== ---Thread-Announcement------------------------------------------
==1359610== 
==1359610== Thread #2 was created
==1359610==    at 0x49A09F3: clone (clone.S:76)
==1359610==    by 0x49A18EE: __clone_internal (clone-internal.c:83)
==1359610==    by 0x490F6D8: create_thread (pthread_create.c:295)
==1359610==    by 0x49101FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==1359610==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x4021E4: ph_threading (threading.c:59)
==1359610==    by 0x40121E: main (main.c:43)
==1359610== 
==1359610== ---Thread-Announcement------------------------------------------
==1359610== 
==1359610== Thread #1 is the program's root thread
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during read of size 4 at 0x4AA7100 by thread #3
==1359610== Locks held: none
==1359610==    at 0x4019E4: ph_seat_on_table (epis_utils.c:30)
==1359610==    by 0x40247C: ph_routine_philos (threading.c:18)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous write of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x4019C6: ph_open_table (epis_utils.c:25)
==1359610==    by 0x4023C7: ph_routine_epis (threading.c:39)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa7100 is 112 bytes inside a block of size 120 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401B09: ph_init_epis (init.c:82)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during read of size 4 at 0x4AA70B4 by thread #3
==1359610== Locks held: none
==1359610==    at 0x402491: ph_routine_philos (threading.c:19)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous write of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x40239F: ph_routine_epis (threading.c:37)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa70b4 is 36 bytes inside a block of size 120 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401B09: ph_init_epis (init.c:82)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during read of size 4 at 0x4AA7100 by thread #3
==1359610== Locks held: none
==1359610==    at 0x4024AE: ph_routine_philos (threading.c:20)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous write of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x4019C6: ph_open_table (epis_utils.c:25)
==1359610==    by 0x4023C7: ph_routine_epis (threading.c:39)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa7100 is 112 bytes inside a block of size 120 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401B09: ph_init_epis (init.c:82)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during write of size 4 at 0x4AA7150 by thread #3
==1359610== Locks held: none
==1359610==    at 0x4013C5: ph_eating (act.c:21)
==1359610==    by 0x4024D2: ph_routine_philos (threading.c:23)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous read of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x4019AA: ph_open_table (epis_utils.c:22)
==1359610==    by 0x4023C7: ph_routine_epis (threading.c:39)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa7150 is 0 bytes inside a block of size 20 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401E85: ph_init_states_meals (init.c:62)
==1359610==    by 0x401B64: ph_init_epis (init.c:87)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during read of size 4 at 0x4AA7100 by thread #3
==1359610== Locks held: none
==1359610==    at 0x4024DB: ph_routine_philos (threading.c:24)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous write of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x4019C6: ph_open_table (epis_utils.c:25)
==1359610==    by 0x4023C7: ph_routine_epis (threading.c:39)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa7100 is 112 bytes inside a block of size 120 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401B09: ph_init_epis (init.c:82)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during write of size 4 at 0x4AA7150 by thread #3
==1359610== Locks held: none
==1359610==    at 0x4014A5: ph_sleeping (act.c:43)
==1359610==    by 0x4024ED: ph_routine_philos (threading.c:25)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous read of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x4019AA: ph_open_table (epis_utils.c:22)
==1359610==    by 0x4023C7: ph_routine_epis (threading.c:39)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa7150 is 0 bytes inside a block of size 20 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401E85: ph_init_states_meals (init.c:62)
==1359610==    by 0x401B64: ph_init_epis (init.c:87)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== ---Thread-Announcement------------------------------------------
==1359610== 
==1359610== Thread #4 was created
==1359610==    at 0x49A09F3: clone (clone.S:76)
==1359610==    by 0x49A18EE: __clone_internal (clone-internal.c:83)
==1359610==    by 0x490F6D8: create_thread (pthread_create.c:295)
==1359610==    by 0x49101FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==1359610==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x40225D: ph_threading (threading.c:64)
==1359610==    by 0x40121E: main (main.c:43)
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during write of size 4 at 0x4AA7154 by thread #4
==1359610== Locks held: none
==1359610==    at 0x401501: ph_sleeping (act.c:50)
==1359610==    by 0x4024ED: ph_routine_philos (threading.c:25)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous read of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x4019AA: ph_open_table (epis_utils.c:22)
==1359610==    by 0x4023C7: ph_routine_epis (threading.c:39)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa7154 is 4 bytes inside a block of size 20 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401E85: ph_init_states_meals (init.c:62)
==1359610==    by 0x401B64: ph_init_epis (init.c:87)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Possible data race during read of size 4 at 0x4AA7100 by thread #4
==1359610== Locks held: none
==1359610==    at 0x4024F6: ph_routine_philos (threading.c:26)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== This conflicts with a previous write of size 4 by thread #2
==1359610== Locks held: none
==1359610==    at 0x4019C6: ph_open_table (epis_utils.c:25)
==1359610==    by 0x4023C7: ph_routine_epis (threading.c:39)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610==  Address 0x4aa7100 is 112 bytes inside a block of size 120 alloc'd
==1359610==    at 0x484A919: malloc (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x401B09: ph_init_epis (init.c:82)
==1359610==    by 0x401ADB: ph_init_sympos (init.c:107)
==1359610==    by 0x401680: ph_args_verif_and_make_sympos (args_verif.c:89)
==1359610==    by 0x4011FA: main (main.c:40)
==1359610==  Block was alloc'd by thread #1
==1359610== 
==1359610== 
==1359610== Process terminating with default action of signal 2 (SIGINT)
==1359610==    at 0x490C117: __futex_abstimed_wait_common64 (futex-internal.c:57)
==1359610==    by 0x490C117: __futex_abstimed_wait_common (futex-internal.c:87)
==1359610==    by 0x490C117: __futex_abstimed_wait_cancelable64 (futex-internal.c:139)
==1359610==    by 0x4911623: __pthread_clockjoin_ex (pthread_join_common.c:105)
==1359610==    by 0x48508F5: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x4022C7: ph_threading (threading.c:71)
==1359610==    by 0x40121E: main (main.c:43)
==1359610== ---Thread-Announcement------------------------------------------
==1359610== 
==1359610== Thread #6 was created
==1359610==    at 0x49A09F3: clone (clone.S:76)
==1359610==    by 0x49A18EE: __clone_internal (clone-internal.c:83)
==1359610==    by 0x490F6D8: create_thread (pthread_create.c:295)
==1359610==    by 0x49101FF: pthread_create@@GLIBC_2.34 (pthread_create.c:828)
==1359610==    by 0x4853767: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x40225D: ph_threading (threading.c:64)
==1359610==    by 0x40121E: main (main.c:43)
==1359610== 
==1359610== ----------------------------------------------------------------
==1359610== 
==1359610== Thread #6: Exiting thread still holds 1 lock
==1359610==    at 0x498F8BF: __libc_write (write.c:26)
==1359610==    by 0x498F8BF: write (write.c:24)
==1359610==    by 0x4905EEC: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1180)
==1359610==    by 0x49079E0: new_do_write (fileops.c:448)
==1359610==    by 0x49079E0: _IO_new_do_write (fileops.c:425)
==1359610==    by 0x49079E0: _IO_do_write@@GLIBC_2.2.5 (fileops.c:422)
==1359610==    by 0x49066D4: _IO_new_file_xsputn (fileops.c:1243)
==1359610==    by 0x49066D4: _IO_file_xsputn@@GLIBC_2.2.5 (fileops.c:1196)
==1359610==    by 0x48F200B: outstring_func (vfprintf-internal.c:239)
==1359610==    by 0x48F200B: __vfprintf_internal (vfprintf-internal.c:1517)
==1359610==    by 0x48DB79E: printf (printf.c:33)
==1359610==    by 0x401A78: ph_speaking (epis_utils.c:40)
==1359610==    by 0x4014D3: ph_sleeping (act.c:44)
==1359610==    by 0x4024ED: ph_routine_philos (threading.c:25)
==1359610==    by 0x485396A: ??? (in /usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so)
==1359610==    by 0x490FAC2: start_thread (pthread_create.c:442)
==1359610==    by 0x49A0A03: clone (clone.S:100)
==1359610== 
==1359610== 
==1359610== Use --history-level=approx or =none to gain increased speed, at
==1359610== the cost of reduced accuracy of conflicting-access information
==1359610== For lists of detected and suppressed errors, rerun with: -s
==1359610== ERROR SUMMARY: 61 errors from 9 contexts (suppressed: 91 from 20)
